// This file auto-generated by ghunit gem
#import <UIKit/UIKit.h>
#import <GHUnit/GHUnit.h>
int main(int argc, char *argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil,NSStringFromClass([GHUnitIOSAppDelegate class]) );
      //@"GHUnitIOSAppDelegate"
  }
}
