# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'HXHTestDemo_3Tests' do
  inherit! :search_paths
  pod 'OCMockito', '~> 4.1.0'
  pod 'OCHamcrest', '~> 6.1.1'
end

